Ubicación y horario terminado
karurosu-vihir/BenditoVerdeHN pull request #10
Opened 2024-11-22 00:24 UTC by Tinoco06

2024-11-22 05:51 UTC, realeoncito approved these changes

2024-11-24 17:37 UTC, realeoncito requested changes
Corregir espacio en blanco ubicado debajo del hero.

2024-11-25 23:45 UTC, realeoncito approved these changes

2024-11-26 00:49 UTC, DenisChavez approved these changes
Todo bien con la página de Ubicacion

2024-11-26 00:55 UTC, karurosu-vihir approved these changes

2024-11-26 00:56 UTC, merged