Josue
karurosu-vihir/BenditoVerdeHN pull request #4
Opened 2024-11-18 03:29 UTC by realeoncito

2024-11-25 03:10 UTC, karurosu-vihir requested changes
En la primera caja hay un mensaje en ingles que habla de framer
Deberias poner un padding bottom a smallCardContainer por que se ve mal que este pegada al footer
No se si es mi navegador pero cuando hago scroll las imagenes del smallCardContainer empiezan a rebotar/temblar

2024-11-25 23:33 UTC, realeoncito reviewed
> En la primera caja hay un mensaje en ingles que habla de framer
Corregido.
> Deberias poner un padding bottom a smallCardContainer por que se ve mal que este pegada al footer
Aplicado
> No se si es mi navegador pero cuando hago scroll las imagenes del smallCardContainer empiezan a rebotar/temblar 
No se pudo replicar, creo que es tema de navegador.

2024-11-26 01:30 UTC, karurosu-vihir approved these changes

2024-11-26 01:47 UTC, DenisChavez approved these changes

2024-11-26 15:53 UTC, merged