Cinthya
karurosu-vihir/BenditoVerdeHN pull request #8
Opened 2024-11-21 06:17 UTC by LizVenus07

Pagina productos nuestros granola unico

2024-11-25 23:52 UTC, realeoncito approved these changes

2024-11-26 00:12 UTC, realeoncito approved these changes

2024-11-26 00:53 UTC, karurosu-vihir requested changes
![image](https://github.com/user-attachments/assets/71f82b69-b82f-47fe-aa42-d8c42325e458)
esto pasa en las resoluciones de 480 a 766 pixeles
Y el fondo es blanco ya habiendo aplicado los cambios del main (no se si lo dejaras asi o le pondras un fondo)

2024-11-26 15:52 UTC, karurosu-vihir approved these changes

2024-11-26 20:59 UTC, merged